### ISSUE TITLE
Multiple GPU's scenario

### ISSUE THREAD

**Issue by lironT74** [canjiali/PARADE#10]
Hello and thank you @canjiali for sharing your code for the PARADE model.

I would like to extend your code to the multiple GPU's scenario. I have successfully ran the whole pipeline (using the pretrained models) on a single GPU. 

I'm new to the tensorflow library, so any guidance of yours will be much appreciated, specifically, with modifying BERT's [`create_optimizer()`](https://github.com/canjiali/PARADE/blob/f330f12a0104c591d871aa54b3b0022dadaef512/bert/optimization.py#L25) function, which is what im stuck at.

I believe that what i'm looking for is an equivalent of [tf.tpu.CrossShardOptimizer(optimizer)](https://github.com/canjiali/PARADE/blob/f330f12a0104c591d871aa54b3b0022dadaef512/bert/optimization.py#L69) for the multiple GPU's scenario, but I was not able to find any "straight forward" replacements.

Thank you again.

**Comment by canjiali** [comment]
hey, thanks for your interest in PARADE. I'm sorry that I have no experience of running TF codes on multiple GPUs. It might be helpful to google something like 'tf estimator multi gpu'.

**Comment by lironT74** [comment]
Got it, thank you.
Another question, why is [this line](https://github.com/canjiali/PARADE/blob/f330f12a0104c591d871aa54b3b0022dadaef512/input_parser.py#L59) needed?

**Comment by canjiali** [comment]
hey, because you want to train for more than one epoch.

**Comment by lironT74** [comment]
Thank you, @canjiali . Could you please share more details? I'm missing something here. Why this line allows for more than one epoch?

**Comment by canjiali** [comment]
please refer to https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/data/TFRecordDataset#repeat

**Comment by lironT74** [comment]
@canjiali Thank you
