### ISSUE TITLE
Generate Data

### ISSUE THREAD

**Issue by Pourbahman** [canjiali/PARADE#11]
Hi,

Thanks for brilliant work.
I want to run your code and I have several issues in data generation part:

0. Generally run.robust04.title.bm25.txt and run.robust04.title.bm25.txt.docno.uniq_rawdocs.txt  are generated with generate_data.py or I should generate them manually?

**If I should generate them manually:**

1. In [https://colab.research.google.com/github/castorini/anserini-notebooks/blob/master/anserini_robust04_demo.ipynb](url)  the file run.robust04.bm25.txt is generated that I do not know whether it is equivalent with run.robust04.title.bm25.txt in run.convert.data.sh or not?

2. run.robust04.bm25.txt contains 242339 lines, I think maybe you sort them and extract just first 1000 rows, don't you?

3. I do not know what is run.robust04.title.bm25.txt.docno.uniq_rawdocs.txt file and how it generates. I think maybe its a text file that each line is (doc number + \t + doc text)  based on unique documents id in run.robust04.title.bm25.txt, isn't it? Also, you told the corpus file can also be extracted by Anserini to form a docno \t content paired text. Would you please explain more about it?

4. When you tell "you need to split the documets into passages, write them into TFrecord files", it means that generate_data.py does it or we should do sth manually?

Thanks

**Comment by Pourbahman** [comment]
Hi,

Excuse me, it is about 3 days that I sent my questions but nobody answer me? Would you please answer me. I have the computational resources for a limited time and, as your code needs GPU memory, if I can not run it now, I get into trouble. 

Thanks for your understanding

**Comment by canjiali** [comment]
Hi, sorry for the inconvenience. I was on vacation.

0. it was generated in other place as explained in the first part in FAQ.
1. they're equivalent.
2. each query has a maximum of 1000 docs (rows).
3. see #0
4. it was done in generate_data.py.

Best,

**Comment by Pourbahman** [comment]
Hey,

Thanks.
About the following question:

In https://colab.research.google.com/github/castorini/anserini-notebooks/blob/master/anserini_robust04_demo.ipynb the file run.robust04.bm25.txt is generated that I do not know whether it is equivalent with run.robust04.title.bm25.txt in run.convert.data.sh or not? 

you told they are equivalent. So, would you please tell me how can I evaluate run.robust04.**desc**.bm25.txt?
Also, what should I change in scripts to have the results for robust04.desc?

Thanks in advance,
Kind Regards

**Comment by canjiali** [comment]
You can simply change your query to the description type. For the other hyper-parameters, please check https://github.com/canjiali/PARADE/issues/5.

**Comment by Pourbahman** [comment]
Thanks but in [https://colab.research.google.com/drive/12fFI-AJS-DN6G3X3pHWYHOnSc0LzgDsN](url) there are not any parameters to be set and I do not see where query should be replaced with description. Would you please explain about it more?

**Comment by canjiali** [comment]
please run `!target/appassembler/bin/SearchCollection` for the help info. you should be able to run the description queries by setting `-topicfield description`

**Comment by Pourbahman** [comment]
Thanks @canjiali 
I used default values for BM25-rm3-title in anserini notebook on robust04 but the MAP and P@20 and nDCG became 0.2903 and 0.3821 and 0.4407, respectively. 

I set the -topicfield description -rm3.fbTerms 20 -bm25prf.b 0.6 -bm25.k1 1.9 in anserini for description but the MAP and P@20 and nDCG became 0.2579 and 0.3502 and 0.4093, respectively. 

These results are not compatible with the reported results on your paper. Would you please tell me what my mistake is?

Thanks

**Comment by canjiali** [comment]
did you try using the default k1 value?

**Comment by Pourbahman** [comment]
For title, yes. This is the original notebook of anserini that I used for title:
[https://colab.research.google.com/github/castorini/anserini-notebooks/blob/master/anserini_robust04_demo.ipynb](url)
But for both I could not get the reported results.

**Comment by canjiali** [comment]
please report your results. you can also try running a grid search varying the k1 and b parameters.
