### ISSUE TITLE
Memory

### ISSUE THREAD

**Issue by Pourbahman** [canjiali/PARADE#13]
Hi,

I sent the first part of your code, that is generate_data, on 500G cpu memory but after generating tfrecords for 5 queries I received out of memory error. How much of memory does it need?

Thanks

**Comment by canjiali** [comment]
Hey, even 50G is enough. can you paste the errors?

**Comment by Pourbahman** [comment]
Hey,

Thanks for your response.
Here is the error:

INFO:tensorflow:Generating data for query 307
I0714 12:53:29.621565 47047353332096 generate_data.py:143] Generating data for query 307
slurmstepd-node008: error: Job 2329413 exceeded memory limit (1073476 > 1048576), being killed
slurmstepd-node008: error: Exceeded job memory limit
slurmstepd-node008: error: *** JOB 2329413 ON node008 CANCELLED AT 2021-07-14T12:53:41 ***
slurmstepd-node008: error: Exceeded step memory limit at some point.

Thanks

**Comment by Pourbahman** [comment]
Hey again,

Here is the link of files that I used for running the script for generating data and you can check it:
https://easyupload.io/m/spzkex

Thanks in advance

**Comment by Pourbahman** [comment]
Hi,

the error happened because of a problem in our server and I ran script run.convert.data.sh on 50G RAM as you told. But when I ran script run.reranking.sh on 15G GPU RAM and 100G CPU RAM I have out of memory problem. As I track memory consumption, it overflow because of CPU RAM. How much of GPU RAM and CPU RAM I need to train your model?

Thanks

**Comment by canjiali** [comment]
CPU memory is used for generating tfrecords.
GPU momory is used for model training, you can try a smaller batch size.
