### ISSUE TITLE
BERT_ckpt

### ISSUE THREAD

**Issue by Pourbahman** [canjiali/PARADE#15]
Hi,

Would you please tell me which one should assign to the export BERT_ckpt:
model.ckpt-400000.data-00000-of-00001
model.ckpt-400000.index
model.ckpt-400000.meta

Maybe it should be ./bert_models_onMSMARCO/vanilla_bert_base_on_MSMARCO/model.ckpt-400000

Am I right?

Thanks in advance

**Comment by canjiali** [comment]
right

**Comment by Pourbahman** [comment]
Thanks!
