### ISSUE TITLE
Smaller sizes ELECTRA models

### ISSUE THREAD

**Issue by lironT74** [canjiali/PARADE#19]
Hi @canjiali,
Have you experimented with smaller sizes of the ELECTRA model?
If so, are the MS MARCO pretrained models available to initialize PARADE?
Otherwise, could you please refer to the code you used to fine tune the ELECTRA model on MS MARCO? (I believe that [this](https://github.com/nyu-dl/dl4marco-bert) is my answer)
Thank you

**Comment by canjiali** [comment]
hey, unfortunately, we didn't train any smaller ELECTRA models. your pointer to the code is correct. when finetuning the ELETRA model, I simply replaced the modeling.py and optimization.py files from the ELECTRA repo.

Best,
Canjia
