### ISSUE TITLE
About Issue #16

### ISSUE THREAD

**Issue by Pourbahman** [canjiali/PARADE#20]
Hi,

In Issue #16, would you please tell me since I want to have scores of train data, when I use unshuffled train data, train_qid_list in these lines of code should be changed in https://github.com/canjiali/PARADE/blob/f330f12a0104c591d871aa54b3b0022dadaef512/run_reranking.py#L343
If yes, would you please tell me what I should change?

(I replied on the related question in issue #16 and I would appreciate it if you check it)

Thanks,
Zahra

**Comment by canjiali** [comment]
hi, the train_qid_list in both generat_data.py and run_reranking.py are sorted so that I don't think you need to do anything else.

**Comment by Pourbahman** [comment]
Thanks!
