### ISSUE TITLE
ClueWeb12B

### ISSUE THREAD

**Issue by lironT74** [canjiali/PARADE#23]
Hi @canjiali, just wanted to ask if you tried running PARADE on the TREC queries of ClueWeb12-B13? Thank you

**Comment by canjiali** [comment]
hey @lironT74 , we have tested PARADE on the ClueWeb12-B13 dataset but not on TREC queries. It's an NTCIR sub-task, you can check the [notebook](https://research.nii.ac.jp/ntcir/workshop/OnlineProceedings15/pdf/ntcir/08-NTCIR15-WWW-LiC.pdf) if you are interested.

**Comment by lironT74** [comment]
@canjiali got it. Thank you!
