### ISSUE TITLE
Dev data in each fold

### ISSUE THREAD

**Issue by Pourbahman** [canjiali/PARADE#24]
Hi

In [https://github.com/canjiali/PARADE/blob/f330f12a0104c591d871aa54b3b0022dadaef512/generate_data.py#L322](url) up to [https://github.com/canjiali/PARADE/blob/f330f12a0104c591d871aa54b3b0022dadaef512/generate_data.py#L360](url) you just generated train and test data and it did not contain validation(dev) data.

Would you please tell me how many queries does train data contain and how many queries test data contain? I want to know if train and test data all together contain all 250 queries of robust04? 

I am looking forward to hearing from you,
Thanks in advance

**Comment by Pourbahman** [comment]
In [https://github.com/canjiali/PARADE/blob/f330f12a0104c591d871aa54b3b0022dadaef512/generate_data.py#L322](url) up to [https://github.com/canjiali/PARADE/blob/f330f12a0104c591d871aa54b3b0022dadaef512/generate_data.py#L360](url) you just generated train and test data and you did not have validation(dev) data.

**Comment by Pourbahman** [comment]
Another question:

Would you please tell me how many queries does train data contain and how many queries does test data contain?
I want to know if train and test data all together contain all 200 queries of robust04 corpus?

**Comment by canjiali** [comment]
The config files are [here](https://github.com/canjiali/PARADE/blob/master/utils/fold_config.py), you can have a look. We didn't use validation data in this repo. The training stops at a fixed number of steps.

**Comment by Pourbahman** [comment]
Thanks.
According to [https://github.com/canjiali/PARADE/blob/master/utils/fold_config.py](url) I think it covers all queries in corpus. Am I right?

**Comment by canjiali** [comment]
right
