### ISSUE TITLE
trec_eval

### ISSUE THREAD

**Issue by Pourbahman** [canjiali/PARADE#26]
Hi,

I want to evaluate model according to [https://github.com/canjiali/PARADE/blob/master/scripts/download_and_evaluate.sh](url). In this script you used /data/tool/trec_eval-9.0.7/trec_eval but I can not find this directory in your repository. Would you please guide me about it?

Thanks in advance,
Kind Regards

**Comment by Pourbahman** [comment]
I am looking forward to hearing from you

**Comment by canjiali** [comment]
please check out https://trec.nist.gov/trec_eval/
