### ISSUE TITLE
Pre-trained BERT

### ISSUE THREAD

**Issue by Pourbahman** [canjiali/PARADE#27]
Hi,

```
export BERT_PRETRAINED_DIR=/content/drive/MyDrive/PARADE-master-2
export BERT_ckpt=${BERT_PRETRAINED_DIR}/vanilla_bert_tiny_on_MSMARCO/model.ckpt-1600000
```

I received this error:

`Unsuccessful TensorSliceReader constructor: Failed to get matching files on /content/drive/MyDrive/PARADE-master-2/vanilla_bert_base_on_MSMARCO/model.ckpt-1600000: Unimplemented: File system scheme '[local]' not implemented (file: '/content/drive/MyDrive/PARADE-master-2/vanilla_bert_base_on_MSMARCO/model.ckpt-1600000')
`

Would you please guide me what the reason is?

Thanks in advance,
Kind regards

**Comment by canjiali** [comment]
It seemed to be a tf issue. please check whether the ckpt exists.

**Comment by Pourbahman** [comment]
Thanks. I checked it. According to [https://www.titanwolf.org/Network/q/07b92709-a9b4-4664-89cd-c85d4f66d38b/y](url) if I used tpu colab to load check point, it needs model to be saved in tpu mode. Would you please tell me if you saved bert check point in tpu mode?

**Comment by Pourbahman** [comment]
Hi,

I concluded that there is no ways except using Google Cloud Storage. Would you please tell me you used TPU on Google Cloud Platform or you used TPU on Colab Pro?

(The reason of my question is TPU on Colab Pro give me just 34GB RAM and I doubt that this would be enough for training your model)

Thanks in advance,
Kind Regards

**Comment by canjiali** [comment]
Hi, we used TPU on Google Cloud Platform. 34GB is enough.
