### ISSUE TITLE
About issue #27

### ISSUE THREAD

**Issue by Pourbahman** [canjiali/PARADE#28]
Hi, 

Would you please tell me do you pay for it? (According to my info I should pay about 2.5 $ hourly)
Also, would you please tell me you used tpu v.3 or tpu v.2?
I read about it but I would appreciate it if you give me any advice about using GCP and challenges you faced to run your code.

Thanks in advance,
Kind Regards

**Comment by canjiali** [comment]
we had a grant and used tpu v3.
