### ISSUE TITLE
Sampling passages should not include the last passage

### ISSUE THREAD

**Issue by lironT74** [canjiali/PARADE#30]
Hi @canjiali ,
I think that the line of code [here](https://github.com/canjiali/PARADE/blob/f330f12a0104c591d871aa54b3b0022dadaef512/generate_data.py#L304) should be replaced with:
`chosen_ids = sorted(random.sample(range(1, len(passages) - 2), FLAGS.max_num_segments_perdoc - 2))`
Do you agree?
Thanks.

**Comment by canjiali** [comment]
hey @lironT74 , the python range(min, max) function exclues the max value, so range(1, len(passages) - 1) should not include the last passage index.

**Comment by lironT74** [comment]
@canjiali you are absolutely right. My bad :)
Thanks!
