### ISSUE TITLE
num of tokens taken from a passage

### ISSUE THREAD

**Issue by lironT74** [canjiali/PARADE#31]
@canjiali Hello, 
I wanted to ask about the  "convert_to_bert_input" function (bert/tokenization), and specifically, [this](https://github.com/canjiali/PARADE/blob/f330f12a0104c591d871aa54b3b0022dadaef512/bert/tokenization.py#L32) line. When add_cls=True we do need to subtract 2 for both CLS and SEP, but when we use this function to convert a passage to tokens we call it with add_cls=False, so we actually need to subtract 1 for SEP only.

It is also visible in the produced tensors:
![image](https://user-images.githubusercontent.com/20051071/145217667-0da79c41-fbd8-44e8-94be-15e31c82a888.png)

whereas if you fix this (by subtracting 1 only if add_cls=False):
![image](https://user-images.githubusercontent.com/20051071/145217783-feb79db1-c1df-4256-beca-b9c8cfff423f.png)

notice that now another token is added before the SEP token (102).

What do you think?
Thanks

**Comment by canjiali** [comment]
hi @lironT74,
Thanks for reporting. I think you're right!
