### ISSUE TITLE
Questions on Reproducing the Results 

### ISSUE THREAD

**Issue by yuhongqian** [canjiali/PARADE#5]
Hi, thank you for posting your great work! 

I have several questions: 
**1. What k1 value did you use for BM25 on Robust04 description?** 
I followed the paper and set b=0.6, and I used Anserini's default k1 value 0.9. The results I got are P@20=0.3233 and nDCG@20=0.3902 (while in the paper P@20=0.3345, nDCG@20=0.4058). 
I was able to get exactly the same results as reported using k1=0.9, b=0.6 using BM25+RM3 on Robust04 description. 

**2. Have you tried running the model on GPU?** 
I tried running electra base model on a single 2080ti, but about 10GB gpu memory is taken up even before training starts. Therefore, I was only able to use `batch_size=1` with `max_seq_length=256`, which I believe is too small to be stable. 
Normally, the machine should be able to handle BERT base with `max_seq_length=256` using `batch_size=16`. 

**3. Loading BERT base checkpoint gave me an error  "tensorflow.python.framework.errors_impl.NotFoundError: Key bert/embeddings/LayerNorm/beta not found in checkpoint".** 
This doesn't happen if I load an electra model. To load the BERT model, I modified `run.reranking.sh` and changed `pretrained_model`  flag to `bert` and `BERT_ckpt` path to the downloaded BERT model. Is there anything I'm missing? 

Some information of my environment: 
python 3.7.9
tensorflow 1.15.0 (not sure if this will be an issue)

Thank you very much in advance!

**Comment by canjiali** [comment]
Hi, thanks for your interest in PARADE.

1. setting k1 = 1.9 and b = 0.6 should give you the same result in the paper. For GOV2 description queries, we set k1 = 2.0 and b = 0.6.

2. Note that for each training instance, PARADE takes 16 segments with max_seq_length=256 for each. So using a batch size of 1 is normal in your case. There are everal ways to speed up your training:
- using the Capreolus toolkit, which has embedded PARADE and tested on GPU. Capreolus also supports early stopping on dev set. The pytorch AMP is also ready, @andrewyates could probably help with AMP if that's what you're looking for. [Capreolus](https://github.com/capreolus-ir/capreolus/blob/master/docs/reproduction/PARADE.md) (Training time: more than one day for each fold)
- using the free Google colab TPU, but you need to have credits to access the google cloud storage. (Training time: 2.5 hours for each fold using TPU v3.8, time doubles using TPU v2.8)
- using the smaller BERT models if you're not pursuing effectiveness. 

3. I checked the checkpoint again and was able to see the missing one you mentioned. A small sample of the variables is given below. However, you can try _tf.reset_default_graph()_ and see if everything works. If not, the BERT-base model [here](https://github.com/nyu-dl/dl4marco-bert) should be equivalent to ours.
```
bert/embeddings/LayerNorm/beta
bert/embeddings/LayerNorm/beta/adam_v
bert/embeddings/LayerNorm/beta/adam_m
bert/embeddings/LayerNorm/gamma/adam_m
bert/embeddings/LayerNorm/gamma/adam_v
bert/embeddings/LayerNorm/gamma
```

Best,
Canjia

**Comment by yuhongqian** [comment]
Thank you very much for your detailed reply! I will try them out.

**Comment by lironT74** [comment]
Thank you again for sharing this awesome work @canjiali.
May I ask, which values of BM25's k1,b,k3 did you use for robust04 title queries?

**Comment by canjiali** [comment]
hey, we used the default parameters in anserini for the title field, which are b = 0.4, k1 = 0.9.

**Comment by lironT74** [comment]
> hey, we used the default parameters in anserini for the title field, which are b = 0.4, k1 = 0.9.

Thank you @canjiali .

**Comment by lironT74** [comment]
@canjiali Another quick question regarding reproducing the results. I assume that you used the original (unstemmed) Title + Description queries (on both datasets), correct?
Thank you.

**Comment by canjiali** [comment]
Those texts are stemmed in the retrieval stage but not for the reranking stage.

**Comment by lironT74** [comment]
Thank you. @canjiali .
Also, is the fine-tuned BERT-Large on MSMARCO available? If so, could you please guide me on where I can download it from?

**Comment by lironT74** [comment]
> Thank you. @canjiali .
> Also, is the fine-tuned BERT-Large on MSMARCO available? If so, could you please guide me on where I can download it from?

I think my answer is the model provided here: https://github.com/nyu-dl/dl4marco-bert#data
correct?

**Comment by canjiali** [comment]
alright, please download from there.

**Comment by lironT74** [comment]
Hello @canjiali (hope you are ok with me asking questions here).
Could you clarify what is the purpose of [this](https://github.com/canjiali/PARADE/blob/f330f12a0104c591d871aa54b3b0022dadaef512/generate_data.py#L171)?
The function seems to be some sort of a sanity check ([here](https://github.com/canjiali/PARADE/blob/f330f12a0104c591d871aa54b3b0022dadaef512/generate_data.py#L208)).

Thank you

**Comment by canjiali** [comment]
Hey, when running on TPU, tf.dataset API will automatically drop the last batch if it's less than the BATCH_SIZE in your setting. So we append some padding examples to ensure that our data not to be dropped accidentally.

**Comment by lironT74** [comment]
All clear. Thank you!
