### ISSUE TITLE
How to get GOV2 datasets.

### ISSUE THREAD

**Issue by haiahaiah** [canjiali/PARADE#7]
Hi, I'm confused about how to get GOV2 datasets. I would appreciate it if you could provide me with the specific process. Thanks a lot.

**Comment by canjiali** [comment]
Hey, did you check the steps at http://ir.dcs.gla.ac.uk/test_collections/access_to_data.html?
The recent [ir_datasets](https://github.com/allenai/ir_datasets) could be helpful if you want to avoid the above step.

Hey @seanmacavaney, is GOV2 completely available now in ir_datasets?

**Comment by seanmacavaney** [comment]
Unfortunately, we cannot _distribute_ the GOV2 documents via ir_datasets-- you still need to go through UoG to get a copy of the dataset.

(Maybe this can change for a collection like GOV2 though? It's big, but I don't think there are the same copyright concerns that exist for collections like the ClueWebs.)

**Comment by haiahaiah** [comment]
> Unfortunately, we cannot _distribute_ the GOV2 documents via ir_datasets-- you still need to go through UoG to get a copy of the dataset.
> 
> (Maybe this can change for a collection like GOV2 though? It's big, but I don't think there are the same copyright concerns that exist for collections like the ClueWebs.)

OK, thanks~
